-- Migration diff: (no schema/snapshot.json yet — diffing against an empty schema) -> the current @three-acts/cms-schema registry.
-- Generated 2026-09-24T11:50:59.500Z by npm run schema:diff / schema:migrate -w @three-acts/api.
-- Review before running against your database (psql or the Supabase SQL editor).

-- This diff is generated by comparing two schema snapshots; it cannot
-- detect renames. A renamed field or collection shows up below as an
-- independent remove + add — review before running, and fold any such
-- pair into a manual `alter ... rename to ...` if that's what happened.
-- Statements starting with `--` are informational only (commented out)
-- and are never executed automatically; they flag destructive changes
-- (dropped tables/columns) for manual opt-in.

-- posts
create table if not exists "posts" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "title" text,
  "slug" text,
  "excerpt" text,
  "body" text,
  "cover_image" text,
  "author" text,
  "tags" text,
  "published_at" timestamptz
);

create unique index if not exists "posts_slug_key" on "posts" ("slug") where "slug" is not null and "slug" <> '';

alter table "posts" drop constraint if exists "posts_publish_status_check";
alter table "posts" add constraint "posts_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_posts_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_posts_updated_at" on "posts";
create trigger "trg_posts_updated_at"
before update on "posts"
for each row
execute function "set_posts_updated_at"();

-- launch-pages
create table if not exists "launch_pages" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "title" text,
  "slug" text,
  "summary" text,
  "template" text,
  "priority" numeric,
  "featured" boolean,
  "hero_image" text,
  "publish_at" timestamptz,
  "record_id" text
);

create unique index if not exists "launch_pages_slug_key" on "launch_pages" ("slug") where "slug" is not null and "slug" <> '';

alter table "launch_pages" drop constraint if exists "launch_pages_template_check";
alter table "launch_pages" add constraint "launch_pages_template_check" check ("template" is null or "template" = '' or "template" in ('campaign', 'editorial', 'conversion', 'long_form', 'product'));

alter table "launch_pages" drop constraint if exists "launch_pages_publish_status_check";
alter table "launch_pages" add constraint "launch_pages_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_launch_pages_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_launch_pages_updated_at" on "launch_pages";
create trigger "trg_launch_pages_updated_at"
before update on "launch_pages"
for each row
execute function "set_launch_pages_updated_at"();

-- content-blocks
create table if not exists "content_blocks" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "block_name" text,
  "slot_key" text,
  "body" text,
  "surface" text,
  "sort_order" numeric,
  "visible" boolean,
  "reference_image" text,
  "review_at" timestamptz,
  "block_id" text
);

create unique index if not exists "content_blocks_slot_key_key" on "content_blocks" ("slot_key") where "slot_key" is not null and "slot_key" <> '';

alter table "content_blocks" drop constraint if exists "content_blocks_surface_check";
alter table "content_blocks" add constraint "content_blocks_surface_check" check ("surface" is null or "surface" = '' or "surface" in ('homepage', 'pricing', 'article', 'checkout', 'email'));

alter table "content_blocks" drop constraint if exists "content_blocks_publish_status_check";
alter table "content_blocks" add constraint "content_blocks_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_content_blocks_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_content_blocks_updated_at" on "content_blocks";
create trigger "trg_content_blocks_updated_at"
before update on "content_blocks"
for each row
execute function "set_content_blocks_updated_at"();

-- product-catalog
create table if not exists "product_catalog" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "sku" text,
  "description" text,
  "price" numeric,
  "category" text,
  "in_stock" boolean,
  "spec_sheet" text,
  "updated_by" text
);

alter table "product_catalog" drop constraint if exists "product_catalog_category_check";
alter table "product_catalog" add constraint "product_catalog_category_check" check ("category" is null or "category" = '' or "category" in ('books', 'workshops', 'templates', 'services', 'bundles'));

alter table "product_catalog" drop constraint if exists "product_catalog_publish_status_check";
alter table "product_catalog" add constraint "product_catalog_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_product_catalog_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_product_catalog_updated_at" on "product_catalog";
create trigger "trg_product_catalog_updated_at"
before update on "product_catalog"
for each row
execute function "set_product_catalog_updated_at"();

-- form-submissions
create table if not exists "form_submissions" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "submitted_by" text,
  "email" text,
  "message" text,
  "source" text,
  "score" numeric,
  "consent" boolean,
  "attachment" text,
  "submitted_at" timestamptz,
  "submission_id" text
);

alter table "form_submissions" drop constraint if exists "form_submissions_source_check";
alter table "form_submissions" add constraint "form_submissions_source_check" check ("source" is null or "source" = '' or "source" in ('homepage', 'pricing', 'webinar', 'partner', 'referral'));

alter table "form_submissions" drop constraint if exists "form_submissions_publish_status_check";
alter table "form_submissions" add constraint "form_submissions_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_form_submissions_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_form_submissions_updated_at" on "form_submissions";
create trigger "trg_form_submissions_updated_at"
before update on "form_submissions"
for each row
execute function "set_form_submissions_updated_at"();

-- experiments
create table if not exists "experiments" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "experiment_name" text,
  "slug" text,
  "hypothesis" text,
  "channel" text,
  "traffic_split" numeric,
  "active" boolean,
  "variant_preview" text,
  "launch_at" timestamptz,
  "experiment_id" text
);

create unique index if not exists "experiments_slug_key" on "experiments" ("slug") where "slug" is not null and "slug" <> '';

alter table "experiments" drop constraint if exists "experiments_channel_check";
alter table "experiments" add constraint "experiments_channel_check" check ("channel" is null or "channel" = '' or "channel" in ('organic', 'paid_search', 'email', 'partner', 'direct'));

alter table "experiments" drop constraint if exists "experiments_publish_status_check";
alter table "experiments" add constraint "experiments_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_experiments_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_experiments_updated_at" on "experiments";
create trigger "trg_experiments_updated_at"
before update on "experiments"
for each row
execute function "set_experiments_updated_at"();

-- locations
create table if not exists "locations" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "location_name" text,
  "slug" text,
  "region" text,
  "capacity" numeric,
  "accepts_bookings" boolean,
  "opening_date" timestamptz,
  "map_preview" text,
  "notes" text
);

create unique index if not exists "locations_slug_key" on "locations" ("slug") where "slug" is not null and "slug" <> '';

alter table "locations" drop constraint if exists "locations_region_check";
alter table "locations" add constraint "locations_region_check" check ("region" is null or "region" = '' or "region" in ('northern', 'eastern', 'western', 'central'));

alter table "locations" drop constraint if exists "locations_publish_status_check";
alter table "locations" add constraint "locations_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_locations_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_locations_updated_at" on "locations";
create trigger "trg_locations_updated_at"
before update on "locations"
for each row
execute function "set_locations_updated_at"();

-- people-directory
create table if not exists "people_directory" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "full_name" text,
  "email" text,
  "bio" text,
  "role" text,
  "weekly_capacity" numeric,
  "contractor" boolean,
  "avatar" text,
  "start_date" timestamptz,
  "person_id" text
);

alter table "people_directory" drop constraint if exists "people_directory_role_check";
alter table "people_directory" add constraint "people_directory_role_check" check ("role" is null or "role" = '' or "role" in ('editor', 'designer', 'developer', 'strategist', 'producer'));

alter table "people_directory" drop constraint if exists "people_directory_publish_status_check";
alter table "people_directory" add constraint "people_directory_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_people_directory_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_people_directory_updated_at" on "people_directory";
create trigger "trg_people_directory_updated_at"
before update on "people_directory"
for each row
execute function "set_people_directory_updated_at"();

-- feature-flags
create table if not exists "feature_flags" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "flag_name" text,
  "key" text,
  "description" text,
  "environment" text,
  "rollout" numeric,
  "enabled" boolean,
  "evidence" text,
  "expires_at" timestamptz,
  "flag_id" text
);

create unique index if not exists "feature_flags_key_key" on "feature_flags" ("key") where "key" is not null and "key" <> '';

alter table "feature_flags" drop constraint if exists "feature_flags_environment_check";
alter table "feature_flags" add constraint "feature_flags_environment_check" check ("environment" is null or "environment" = '' or "environment" in ('development', 'staging', 'production', 'preview'));

alter table "feature_flags" drop constraint if exists "feature_flags_publish_status_check";
alter table "feature_flags" add constraint "feature_flags_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_feature_flags_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_feature_flags_updated_at" on "feature_flags";
create trigger "trg_feature_flags_updated_at"
before update on "feature_flags"
for each row
execute function "set_feature_flags_updated_at"();

-- media-library
create table if not exists "media_library" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "asset_name" text,
  "alt_text" text,
  "license" text,
  "width" numeric,
  "height" numeric,
  "sensitive" boolean,
  "file" text,
  "uploaded_at" timestamptz,
  "asset_id" text
);

alter table "media_library" drop constraint if exists "media_library_license_check";
alter table "media_library" add constraint "media_library_license_check" check ("license" is null or "license" = '' or "license" in ('owned', 'licensed', 'creative_commons', 'unknown'));

alter table "media_library" drop constraint if exists "media_library_publish_status_check";
alter table "media_library" add constraint "media_library_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_media_library_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_media_library_updated_at" on "media_library";
create trigger "trg_media_library_updated_at"
before update on "media_library"
for each row
execute function "set_media_library_updated_at"();

-- redirect-rules
create table if not exists "redirect_rules" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "source_path" text,
  "target_url" text,
  "notes" text,
  "status_code" text,
  "hits" numeric,
  "permanent" boolean,
  "evidence" text,
  "last_hit_at" timestamptz,
  "rule_id" text
);

create unique index if not exists "redirect_rules_source_path_key" on "redirect_rules" ("source_path") where "source_path" is not null and "source_path" <> '';

alter table "redirect_rules" drop constraint if exists "redirect_rules_status_code_check";
alter table "redirect_rules" add constraint "redirect_rules_status_code_check" check ("status_code" is null or "status_code" = '' or "status_code" in ('301', '302', '307', '308'));

alter table "redirect_rules" drop constraint if exists "redirect_rules_publish_status_check";
alter table "redirect_rules" add constraint "redirect_rules_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_redirect_rules_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_redirect_rules_updated_at" on "redirect_rules";
create trigger "trg_redirect_rules_updated_at"
before update on "redirect_rules"
for each row
execute function "set_redirect_rules_updated_at"();

-- localization-strings
create table if not exists "localization_strings" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "string_key" text,
  "localized_text" text,
  "locale" text,
  "namespace" text,
  "character_limit" numeric,
  "approved" boolean,
  "screenshot" text,
  "source_updated_at" timestamptz,
  "string_id" text
);

alter table "localization_strings" drop constraint if exists "localization_strings_locale_check";
alter table "localization_strings" add constraint "localization_strings_locale_check" check ("locale" is null or "locale" = '' or "locale" in ('en', 'af', 'xh', 'fr', 'de'));

alter table "localization_strings" drop constraint if exists "localization_strings_namespace_check";
alter table "localization_strings" add constraint "localization_strings_namespace_check" check ("namespace" is null or "namespace" = '' or "namespace" in ('navigation', 'forms', 'checkout', 'seo', 'errors'));

alter table "localization_strings" drop constraint if exists "localization_strings_publish_status_check";
alter table "localization_strings" add constraint "localization_strings_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_localization_strings_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_localization_strings_updated_at" on "localization_strings";
create trigger "trg_localization_strings_updated_at"
before update on "localization_strings"
for each row
execute function "set_localization_strings_updated_at"();
