-- Migration diff: apps/api/schema/snapshot.json -> the current @three-acts/cms-schema registry.
-- Generated 2026-09-25T12:11:26.543Z by npm run schema:diff / schema:migrate -w @three-acts/api.
-- Review before running against your database (psql or the Supabase SQL editor).

-- This diff is generated by comparing two schema snapshots; it cannot
-- detect renames. A renamed field or collection shows up below as an
-- independent remove + add — review before running, and fold any such
-- pair into a manual `alter ... rename to ...` if that's what happened.
-- Statements starting with `--` are informational only (commented out)
-- and are never executed automatically; they flag destructive changes
-- (dropped tables/columns) for manual opt-in.

-- WARNING: "cms_users" was removed from the registry. Dropping it is
-- destructive (data loss) and left commented out — uncomment only if
-- you're sure the table (and its data) should go away:
-- drop table if exists "cms_users";

alter table "product_reviews" add column if not exists "source" text;

alter table "product_reviews" drop constraint if exists "product_reviews_source_check";
alter table "product_reviews" add constraint "product_reviews_source_check" check ("source" is null or "source" = '' or "source" in ('site', 'manual'));

alter table "orders" add column if not exists "items" text;

alter table "orders" add column if not exists "shipping_name" text;

alter table "orders" add column if not exists "shipping_address" text;

alter table "orders" add column if not exists "shipping_postal_code" text;

alter table "orders" add column if not exists "customer_phone" text;

alter table "customers" add column if not exists "address" text;

alter table "customers" add column if not exists "postal_code" text;

-- WARNING: "form_submissions"."source" was removed from the registry.
-- Dropping it is destructive (data loss) and left commented out:
-- alter table "form_submissions" drop column if exists "source";

alter table "form_submissions" add column if not exists "form" text;

alter table "form_submissions" drop constraint if exists "form_submissions_form_check";
alter table "form_submissions" add constraint "form_submissions_form_check" check ("form" is null or "form" = '' or "form" in ('contact', 'newsletter', 'inquiry'));

alter table "form_submissions" add column if not exists "company" text;

alter table "form_submissions" add column if not exists "phone" text;
