-- Migration diff: apps/api/schema/snapshot.json -> the current @three-acts/cms-schema registry.
-- Generated 2026-09-25T11:10:08.918Z by npm run schema:diff / schema:migrate -w @three-acts/api.
-- Review before running against your database (psql or the Supabase SQL editor).

-- This diff is generated by comparing two schema snapshots; it cannot
-- detect renames. A renamed field or collection shows up below as an
-- independent remove + add — review before running, and fold any such
-- pair into a manual `alter ... rename to ...` if that's what happened.
-- Statements starting with `--` are informational only (commented out)
-- and are never executed automatically; they flag destructive changes
-- (dropped tables/columns) for manual opt-in.

-- articles
create table if not exists "articles" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "title" text,
  "slug" text,
  "excerpt" text,
  "body" text,
  "cover_image" text,
  "author" text,
  "category" text,
  "tags" text,
  "published_at" timestamptz,
  "reading_time" numeric,
  "featured" boolean,
  "seo_title" text,
  "seo_description" text
);

create unique index if not exists "articles_slug_key" on "articles" ("slug") where "slug" is not null and "slug" <> '';

alter table "articles" drop constraint if exists "articles_publish_status_check";
alter table "articles" add constraint "articles_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_articles_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_articles_updated_at" on "articles";
create trigger "trg_articles_updated_at"
before update on "articles"
for each row
execute function "set_articles_updated_at"();

-- authors
create table if not exists "authors" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "slug" text,
  "role" text,
  "bio" text,
  "avatar" text,
  "email" text,
  "website_url" text,
  "x_handle" text,
  "instagram_handle" text,
  "linkedin_url" text
);

create unique index if not exists "authors_slug_key" on "authors" ("slug") where "slug" is not null and "slug" <> '';

create unique index if not exists "authors_email_key" on "authors" ("email") where "email" is not null and "email" <> '';

alter table "authors" drop constraint if exists "authors_publish_status_check";
alter table "authors" add constraint "authors_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_authors_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_authors_updated_at" on "authors";
create trigger "trg_authors_updated_at"
before update on "authors"
for each row
execute function "set_authors_updated_at"();

-- article-categories
create table if not exists "article_categories" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "slug" text,
  "description" text,
  "sort_order" numeric
);

create unique index if not exists "article_categories_slug_key" on "article_categories" ("slug") where "slug" is not null and "slug" <> '';

alter table "article_categories" drop constraint if exists "article_categories_publish_status_check";
alter table "article_categories" add constraint "article_categories_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_article_categories_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_article_categories_updated_at" on "article_categories";
create trigger "trg_article_categories_updated_at"
before update on "article_categories"
for each row
execute function "set_article_categories_updated_at"();

-- faqs
create table if not exists "faqs" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "question" text,
  "answer" text,
  "topic" text,
  "sort_order" numeric
);

alter table "faqs" drop constraint if exists "faqs_topic_check";
alter table "faqs" add constraint "faqs_topic_check" check ("topic" is null or "topic" = '' or "topic" in ('general', 'orders', 'shipping', 'returns', 'products', 'account'));

alter table "faqs" drop constraint if exists "faqs_publish_status_check";
alter table "faqs" add constraint "faqs_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_faqs_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_faqs_updated_at" on "faqs";
create trigger "trg_faqs_updated_at"
before update on "faqs"
for each row
execute function "set_faqs_updated_at"();

-- testimonials
create table if not exists "testimonials" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "customer_name" text,
  "quote" text,
  "customer_title" text,
  "company" text,
  "avatar" text,
  "rating" text,
  "product" text,
  "featured" boolean,
  "sort_order" numeric
);

alter table "testimonials" drop constraint if exists "testimonials_rating_check";
alter table "testimonials" add constraint "testimonials_rating_check" check ("rating" is null or "rating" = '' or "rating" in ('5', '4', '3', '2', '1'));

alter table "testimonials" drop constraint if exists "testimonials_publish_status_check";
alter table "testimonials" add constraint "testimonials_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_testimonials_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_testimonials_updated_at" on "testimonials";
create trigger "trg_testimonials_updated_at"
before update on "testimonials"
for each row
execute function "set_testimonials_updated_at"();

-- products
create table if not exists "products" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "title" text,
  "slug" text,
  "sku" text,
  "category" text,
  "price" numeric,
  "compare_at_price" numeric,
  "currency" text,
  "inventory" numeric,
  "availability" text,
  "short_description" text,
  "description" text,
  "images" text,
  "product_video" text,
  "spec_sheet" text,
  "weight_grams" numeric,
  "tags" text,
  "featured" boolean
);

create unique index if not exists "products_slug_key" on "products" ("slug") where "slug" is not null and "slug" <> '';

create unique index if not exists "products_sku_key" on "products" ("sku") where "sku" is not null and "sku" <> '';

alter table "products" drop constraint if exists "products_currency_check";
alter table "products" add constraint "products_currency_check" check ("currency" is null or "currency" = '' or "currency" in ('ZAR', 'USD', 'EUR', 'GBP'));

alter table "products" drop constraint if exists "products_availability_check";
alter table "products" add constraint "products_availability_check" check ("availability" is null or "availability" = '' or "availability" in ('in_stock', 'low_stock', 'out_of_stock', 'preorder', 'discontinued'));

alter table "products" drop constraint if exists "products_publish_status_check";
alter table "products" add constraint "products_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_products_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_products_updated_at" on "products";
create trigger "trg_products_updated_at"
before update on "products"
for each row
execute function "set_products_updated_at"();

-- product-categories
create table if not exists "product_categories" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "slug" text,
  "description" text,
  "image" text,
  "sort_order" numeric
);

create unique index if not exists "product_categories_slug_key" on "product_categories" ("slug") where "slug" is not null and "slug" <> '';

alter table "product_categories" drop constraint if exists "product_categories_publish_status_check";
alter table "product_categories" add constraint "product_categories_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_product_categories_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_product_categories_updated_at" on "product_categories";
create trigger "trg_product_categories_updated_at"
before update on "product_categories"
for each row
execute function "set_product_categories_updated_at"();

-- product-reviews
create table if not exists "product_reviews" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "title" text,
  "product" text,
  "customer_name" text,
  "customer_email" text,
  "rating" text,
  "body" text,
  "verified_purchase" boolean,
  "approved" boolean,
  "submitted_at" timestamptz
);

alter table "product_reviews" drop constraint if exists "product_reviews_rating_check";
alter table "product_reviews" add constraint "product_reviews_rating_check" check ("rating" is null or "rating" = '' or "rating" in ('5', '4', '3', '2', '1'));

alter table "product_reviews" drop constraint if exists "product_reviews_publish_status_check";
alter table "product_reviews" add constraint "product_reviews_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_product_reviews_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_product_reviews_updated_at" on "product_reviews";
create trigger "trg_product_reviews_updated_at"
before update on "product_reviews"
for each row
execute function "set_product_reviews_updated_at"();

-- orders
create table if not exists "orders" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "order_number" text,
  "customer_email" text,
  "customer_name" text,
  "status" text,
  "payment_status" text,
  "payment_method" text,
  "item_count" numeric,
  "subtotal" numeric,
  "discount_total" numeric,
  "discount_code" text,
  "tax_total" numeric,
  "shipping_total" numeric,
  "total" numeric,
  "currency" text,
  "placed_at" timestamptz,
  "shipping_city" text,
  "shipping_country" text,
  "tracking_number" text,
  "notes" text
);

create unique index if not exists "orders_order_number_key" on "orders" ("order_number") where "order_number" is not null and "order_number" <> '';

alter table "orders" drop constraint if exists "orders_status_check";
alter table "orders" add constraint "orders_status_check" check ("status" is null or "status" = '' or "status" in ('pending', 'paid', 'fulfilled', 'shipped', 'refunded', 'cancelled'));

alter table "orders" drop constraint if exists "orders_payment_status_check";
alter table "orders" add constraint "orders_payment_status_check" check ("payment_status" is null or "payment_status" = '' or "payment_status" in ('awaiting', 'authorized', 'paid', 'partially_refunded', 'refunded', 'failed'));

alter table "orders" drop constraint if exists "orders_payment_method_check";
alter table "orders" add constraint "orders_payment_method_check" check ("payment_method" is null or "payment_method" = '' or "payment_method" in ('card', 'eft', 'paypal', 'apple_pay', 'gift_card'));

alter table "orders" drop constraint if exists "orders_currency_check";
alter table "orders" add constraint "orders_currency_check" check ("currency" is null or "currency" = '' or "currency" in ('ZAR', 'USD', 'EUR', 'GBP'));

alter table "orders" drop constraint if exists "orders_publish_status_check";
alter table "orders" add constraint "orders_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_orders_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_orders_updated_at" on "orders";
create trigger "trg_orders_updated_at"
before update on "orders"
for each row
execute function "set_orders_updated_at"();

-- customers
create table if not exists "customers" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "email" text,
  "phone" text,
  "city" text,
  "country" text,
  "marketing_opt_in" boolean,
  "total_orders" numeric,
  "lifetime_value" numeric,
  "first_order_at" timestamptz,
  "last_order_at" timestamptz,
  "notes" text
);

create unique index if not exists "customers_email_key" on "customers" ("email") where "email" is not null and "email" <> '';

alter table "customers" drop constraint if exists "customers_publish_status_check";
alter table "customers" add constraint "customers_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_customers_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_customers_updated_at" on "customers";
create trigger "trg_customers_updated_at"
before update on "customers"
for each row
execute function "set_customers_updated_at"();

-- discount-codes
create table if not exists "discount_codes" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "code" text,
  "description" text,
  "discount_type" text,
  "amount" numeric,
  "minimum_subtotal" numeric,
  "usage_limit" numeric,
  "times_used" numeric,
  "starts_at" timestamptz,
  "ends_at" timestamptz,
  "active" boolean
);

create unique index if not exists "discount_codes_code_key" on "discount_codes" ("code") where "code" is not null and "code" <> '';

alter table "discount_codes" drop constraint if exists "discount_codes_discount_type_check";
alter table "discount_codes" add constraint "discount_codes_discount_type_check" check ("discount_type" is null or "discount_type" = '' or "discount_type" in ('percentage', 'fixed_amount', 'free_shipping'));

alter table "discount_codes" drop constraint if exists "discount_codes_publish_status_check";
alter table "discount_codes" add constraint "discount_codes_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_discount_codes_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_discount_codes_updated_at" on "discount_codes";
create trigger "trg_discount_codes_updated_at"
before update on "discount_codes"
for each row
execute function "set_discount_codes_updated_at"();

-- cms-users
create table if not exists "cms_users" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "name" text,
  "email" text,
  "role" text,
  "status" text,
  "author_slug" text,
  "avatar" text,
  "last_active_at" timestamptz
);

create unique index if not exists "cms_users_email_key" on "cms_users" ("email") where "email" is not null and "email" <> '';

alter table "cms_users" drop constraint if exists "cms_users_role_check";
alter table "cms_users" add constraint "cms_users_role_check" check ("role" is null or "role" = '' or "role" in ('admin', 'editor', 'author', 'viewer'));

alter table "cms_users" drop constraint if exists "cms_users_status_check";
alter table "cms_users" add constraint "cms_users_status_check" check ("status" is null or "status" = '' or "status" in ('active', 'invited', 'suspended'));

alter table "cms_users" drop constraint if exists "cms_users_publish_status_check";
alter table "cms_users" add constraint "cms_users_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

create or replace function "set_cms_users_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_cms_users_updated_at" on "cms_users";
create trigger "trg_cms_users_updated_at"
before update on "cms_users"
for each row
execute function "set_cms_users_updated_at"();

-- "posts" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "posts";

-- "launch_pages" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "launch_pages";

-- "content_blocks" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "content_blocks";

-- "product_catalog" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "product_catalog";

-- "experiments" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "experiments";

-- "locations" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "locations";

-- "people_directory" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "people_directory";

-- "feature_flags" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "feature_flags";

-- "localization_strings" was removed from the registry (demo data; intentionally dropped —
-- hand-uncommented from the generated migration).
drop table if exists "localization_strings";

-- Hand-added: clear legacy source values (homepage/pricing/webinar/partner/referral)
-- that the new check constraint below would reject.
update "form_submissions" set "source" = '' where "source" is not null and "source" not in ('contact', 'newsletter', 'product_enquiry', 'wholesale', 'support');
alter table "form_submissions" drop constraint if exists "form_submissions_source_check";
alter table "form_submissions" add constraint "form_submissions_source_check" check ("source" is null or "source" = '' or "source" in ('contact', 'newsletter', 'product_enquiry', 'wholesale', 'support'));

alter table "form_submissions" drop constraint if exists "form_submissions_publish_status_check";
alter table "form_submissions" add constraint "form_submissions_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

alter table "media_library" drop constraint if exists "media_library_publish_status_check";
alter table "media_library" add constraint "media_library_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

alter table "redirect_rules" drop constraint if exists "redirect_rules_publish_status_check";
alter table "redirect_rules" add constraint "redirect_rules_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

alter table "site_settings" drop constraint if exists "site_settings_publish_status_check";
alter table "site_settings" add constraint "site_settings_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));

alter table "page_settings" drop constraint if exists "page_settings_publish_status_check";
alter table "page_settings" add constraint "page_settings_publish_status_check" check ("publish_status" in ('published', 'draft', 'queued_to_publish', 'not_published'));
