-- Migration diff: apps/api/schema/snapshot.json -> the current @three-acts/cms-schema registry.
-- Generated 2026-09-25T08:44:28.214Z by npm run schema:diff / schema:migrate -w @three-acts/api.
-- Review before running against your database (psql or the Supabase SQL editor).

-- This diff is generated by comparing two schema snapshots; it cannot
-- detect renames. A renamed field or collection shows up below as an
-- independent remove + add — review before running, and fold any such
-- pair into a manual `alter ... rename to ...` if that's what happened.
-- Statements starting with `--` are informational only (commented out)
-- and are never executed automatically; they flag destructive changes
-- (dropped tables/columns) for manual opt-in.

-- site-settings
create table if not exists "site_settings" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "site_name" text,
  "title_template" text,
  "default_meta_description" text,
  "default_og_image" text,
  "favicon" text,
  "twitter_handle" text,
  "locale" text,
  "allow_indexing" boolean,
  "schema_markup" text
);

alter table "site_settings" drop constraint if exists "site_settings_publish_status_check";
alter table "site_settings" add constraint "site_settings_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_site_settings_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_site_settings_updated_at" on "site_settings";
create trigger "trg_site_settings_updated_at"
before update on "site_settings"
for each row
execute function "set_site_settings_updated_at"();

-- page-settings
create table if not exists "page_settings" (
  "id" uuid primary key default gen_random_uuid(),
  "publish_status" text not null default 'not_published',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "page_name" text,
  "page_path" text,
  "meta_title" text,
  "meta_description" text,
  "canonical_url" text,
  "og_title" text,
  "og_description" text,
  "og_image" text,
  "search_title" text,
  "search_description" text,
  "search_image" text,
  "schema_markup" text
);

create unique index if not exists "page_settings_page_path_key" on "page_settings" ("page_path") where "page_path" is not null and "page_path" <> '';

alter table "page_settings" drop constraint if exists "page_settings_publish_status_check";
alter table "page_settings" add constraint "page_settings_publish_status_check" check ("publish_status" in ('published', 'not_published', 'queued_to_publish'));

create or replace function "set_page_settings_updated_at"()
returns trigger as $$
begin
  new."updated_at" = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists "trg_page_settings_updated_at" on "page_settings";
create trigger "trg_page_settings_updated_at"
before update on "page_settings"
for each row
execute function "set_page_settings_updated_at"();
