-- Migration diff: apps/api/schema/snapshot.json -> the current @three-acts/cms-schema registry.
-- Generated 2026-09-25T05:38:41.669Z by npm run schema:diff / schema:migrate -w @three-acts/api.
-- Review before running against your database (psql or the Supabase SQL editor).

-- This diff is generated by comparing two schema snapshots; it cannot
-- detect renames. A renamed field or collection shows up below as an
-- independent remove + add — review before running, and fold any such
-- pair into a manual `alter ... rename to ...` if that's what happened.
-- Statements starting with `--` are informational only (commented out)
-- and are never executed automatically; they flag destructive changes
-- (dropped tables/columns) for manual opt-in.

alter table "launch_pages" add column if not exists "image_gallery" text;
